version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp_test
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - .:/var/www/html/wp-content/plugins/nuclear-engagement
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_test
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wpcli:
    image: wordpress:cli
    container_name: wpcli_test
    volumes:
      - .:/var/www/html/wp-content/plugins/nuclear-engagement
    depends_on:
      - wordpress
      - db
    command: >
      /bin/sh -c "
      sleep 30;
      wp core install --path=/var/www/html --url=localhost:8080 --title='Test Site' --admin_user=admin --admin_password=admin --admin_email=admin@test.com --allow-root;
      wp plugin activate nuclear-engagement --allow-root;
      "

volumes:
  db_data: