import{e as z}from"../../logger-aBgireju.js";window.NuclenLazyLoadComponent=function(i,n=null){const t=document.getElementById(i);if(!t)return;const e=new IntersectionObserver(s=>{s.forEach(l=>{if(l.isIntersecting){const o=window;n&&typeof o[n]=="function"&&o[n](),e.disconnect()}})},{rootMargin:"0px 0px -200px 0px",threshold:.1});e.observe(t)};function E(i,n){const t=document.querySelector(i);if(!t)return;new IntersectionObserver((s,l)=>{s.forEach(o=>{o.isIntersecting&&o.intersectionRatio===1&&(typeof gtag=="function"&&gtag("event",n),l.unobserve(o.target))})},{root:null,rootMargin:"0px",threshold:1}).observe(t)}const k=new MutationObserver((i,n)=>{const t=document.getElementById("nuclen-quiz-container"),e=document.getElementById("nuclen-summary-container");t&&e&&(E("#nuclen-summary-container","nuclen_summary_view"),E("#nuclen-quiz-container","nuclen_quiz_view"),n.disconnect())});k.observe(document.body,{childList:!0,subtree:!0});window.NuclenLazyLoadComponent("nuclen-quiz-container","nuclearEngagementInitQuiz");function N(i){const n=[...i];for(let t=n.length-1;t>0;t--){const e=Math.floor(Math.random()*(t+1));[n[t],n[e]]=[n[e],n[t]]}return n}const L=i=>/.+@.+\..+/.test(i),g=i=>i.replace(/[&<>"']/g,n=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[n]||n),x=async(i,n,t,e)=>{if(!(!e.ajaxUrl||!e.ajaxNonce))try{const s=await fetch(e.ajaxUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({action:"nuclen_save_optin",nonce:e.ajaxNonce,name:i,email:n,url:t})});s.ok||z("[NE] Local opt-in failed",s.status)}catch(s){z("[NE] Local opt-in network error",s)}},I=async(i,n,t)=>{if(t.webhook)try{const e=await fetch(t.webhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:i,email:n})});if(!e.ok)throw z("[NE] Webhook responded with",e.status),new Error(String(e.status))}catch(e){throw z("[NE] Webhook request error",e),e}},B=i=>`
	<div id="nuclen-optin-container" class="nuclen-optin-with-results">
	<p class="nuclen-fg"><strong>${i.promptText}</strong></p>
	<label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
	<input  type="text"  id="nuclen-optin-name">
	<label for="nuclen-optin-email" class="nuclen-fg">Email</label>
	<input  type="email" id="nuclen-optin-email" required>
	<button type="button" id="nuclen-optin-submit">${i.submitLabel}</button>
	</div>`;function $(i,n,t,e){var s,l;i.innerHTML=`
	<div id="nuclen-optin-container">
		<p class="nuclen-fg"><strong>${n.promptText}</strong></p>
		<label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
		<input  type="text"  id="nuclen-optin-name">
		<label for="nuclen-optin-email" class="nuclen-fg">Email *</label>
		<input  type="email" id="nuclen-optin-email" required>
		<div class="nuclen-optin-btn-row">
		<button type="button" id="nuclen-optin-submit">${n.submitLabel}</button>
		</div>
		${n.mandatory?"":'<div class="nuclen-optin-skip"><a href="#" id="nuclen-optin-skip">Skip &amp; view results</a></div>'}
	</div>`,(s=document.getElementById("nuclen-optin-submit"))==null||s.addEventListener("click",async()=>{const o=document.getElementById("nuclen-optin-name").value.trim(),m=document.getElementById("nuclen-optin-email").value.trim();if(!L(m))return alert("Please enter a valid email");await x(o,m,window.location.href,n);try{await I(o,m,n),t()}catch{alert("Network error – please try again later.")}}),(l=document.getElementById("nuclen-optin-skip"))==null||l.addEventListener("click",o=>{o.preventDefault(),e()})}function _(i){var n;(n=document.getElementById("nuclen-optin-submit"))==null||n.addEventListener("click",async()=>{const t=document.getElementById("nuclen-optin-name").value.trim(),e=document.getElementById("nuclen-optin-email").value.trim();if(!L(e))return alert("Please enter a valid email");await x(t,e,window.location.href,i);try{await I(t,e,i)}catch{alert("Unable to submit. Please try later.")}})}function T(i,n,t){let e="";i.enabled&&i.position==="with_results"&&(e+=B(i)),e+=`
<div id="nuclen-quiz-results-title" class="nuclen-fg">${NuclenStrings.your_score}</div>
<div id="nuclen-quiz-results-score" class="nuclen-fg" aria-live="polite" aria-atomic="true">
${t.score} / ${n.length}
</div>`;const s=t.score===n.length?NuclenStrings.perfect:t.score>n.length/2?NuclenStrings.well_done:NuclenStrings.retake_prompt;return e+=`<div id="nuclen-quiz-score-comment" aria-live="polite">${s}</div>`,e+='<div id="nuclen-quiz-result-tabs-container">',n.forEach((l,o)=>{e+=`
<button class="nuclen-quiz-result-tab" onclick="nuclearEngagementShowQuizQuestionDetails(${o})">${o+1}</button>`}),e+='</div><div id="nuclen-quiz-result-details-container" class="nuclen-fg dashboard-box"></div>',NuclenCustomQuizHtmlAfter!=null&&NuclenCustomQuizHtmlAfter.trim()&&(e+=`
<div id="nuclen-quiz-end-message" class="nuclen-fg">
${NuclenCustomQuizHtmlAfter}
</div>`),e+=`
<button id="nuclen-quiz-retake-button" onclick="nuclearEngagementRetakeQuiz()">${NuclenStrings.retake_test}</button>`,e}function C(i,n){window.nuclearEngagementShowQuizQuestionDetails=t=>{var l;const e=i[t],s=n.userAnswers[t];document.getElementById("nuclen-quiz-result-details-container").innerHTML=`
<p class="nuclen-quiz-detail-question">${g(e.question)}</p>
<p class="nuclen-quiz-detail-correct"><strong>${NuclenStrings.correct}</strong> ${g(e.answers[0])}</p>
${s===0?`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${g(e.answers[0])} <span class="nuclen-quiz-checkmark">✔️</span></p>`:`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${g(e.answers[s]??"[No data]")}</p>`}
<p class="nuclen-quiz-detail-explanation">${g(e.explanation)}</p>`,Array.from(document.getElementsByClassName("nuclen-quiz-result-tab")).forEach(o=>o.classList.remove("nuclen-quiz-result-active-tab")),(l=document.getElementsByClassName("nuclen-quiz-result-tab")[t])==null||l.classList.add("nuclen-quiz-result-active-tab")},window.nuclearEngagementShowQuizQuestionDetails(0)}function H(i,n,t,e,s){window.nuclearEngagementRetakeQuiz=()=>{i.currIdx=0,i.score=0,i.userAnswers.length=0,n.innerHTML="",n.classList.add("nuclen-quiz-hidden"),t.style.width=`${1/e*100}%`,s()}}function M(i,n,t){const{qContainer:e,aContainer:s,explContainer:l,nextBtn:o,finalContainer:m}=i;e.innerHTML="",s.innerHTML="",l.innerHTML="",o.classList.add("nuclen-quiz-hidden"),$(m,n,t,t)}function O(i,n,t,e,s){const{qContainer:l,aContainer:o,explContainer:m,nextBtn:h,finalContainer:u,progBar:d}=i;l.innerHTML="",o.innerHTML="",m.innerHTML="",h.classList.add("nuclen-quiz-hidden"),u.classList.remove("nuclen-quiz-hidden"),u.innerHTML=T(n,t,e),u.setAttribute("aria-live","polite"),n.enabled&&n.position==="with_results"&&_(n),C(t,e),H(e,u,d,t.length,s),typeof gtag=="function"&&gtag("event","nuclen_quiz_end")}function S(i,n,t){i.style.width=`${(n+1)/t*100}%`}function q(i,n,t,e){const{qContainer:s,aContainer:l,explContainer:o,nextBtn:m,progBar:h}=t,u=i[n.currIdx];s.innerHTML=`
	<div id="nuclen-quiz-question-number" aria-live="polite" aria-atomic="true">
		${n.currIdx+1}/${i.length}
	</div>
	<div class="nuclen-quiz-title" role="heading" aria-level="2">${g(u.question)}</div>`;const d=N(u.answers.map((r,a)=>({ans:r,idx:a})).filter(r=>r.ans.trim()));l.innerHTML=d.map((r,a)=>`
		<button
			class="nuclen-quiz-answer-button nuclen-quiz-possible-answer"
			data-orig-idx="${r.idx}"
			tabindex="0"
			aria-label="Answer ${a+1}: ${g(r.ans)}"
		>${g(r.ans)}</button>`).join("");const f=d.findIndex(r=>r.idx===0);o.innerHTML="",o.classList.add("nuclen-quiz-hidden"),m.classList.add("nuclen-quiz-hidden"),S(h,n.currIdx,i.length);const c=r=>{const a=parseInt(r.getAttribute("data-orig-idx")||"0",10);e(a,d.findIndex(y=>y.idx===a),f),l.removeEventListener("click",w),l.removeEventListener("keydown",v)},w=r=>{const a=r.target;a.matches("button.nuclen-quiz-answer-button")&&c(a)},v=r=>{const a=r.target;a.matches("button.nuclen-quiz-answer-button")&&(r.key==="Enter"||r.key===" ")&&(r.preventDefault(),c(a))};l.addEventListener("click",w),l.addEventListener("keydown",v)}function Q(){const i=document.getElementById("nuclen-quiz-container"),n=document.getElementById("nuclen-quiz-question-container"),t=document.getElementById("nuclen-quiz-answers-container"),e=document.getElementById("nuclen-quiz-progress-bar"),s=document.getElementById("nuclen-quiz-final-result-container"),l=document.getElementById("nuclen-quiz-next-button"),o=document.getElementById("nuclen-quiz-explanation-container");if(!i||!n||!t||!e||!s||!l||!o)return;const m=(NuclenSettings==null?void 0:NuclenSettings.questions_per_quiz)??10,h=(NuclenSettings==null?void 0:NuclenSettings.answers_per_question)??4,u={position:NuclenOptinPosition??"with_results",mandatory:!!NuclenOptinMandatory,promptText:NuclenOptinPromptText,submitLabel:NuclenOptinButtonText,enabled:!!window.NuclenOptinEnabled,webhook:window.NuclenOptinWebhook??"",ajaxUrl:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.url)??"",ajaxNonce:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.nonce)??""},d=postQuizData.filter(r=>{var a;return r.question.trim()&&((a=r.answers[0])==null?void 0:a.trim())}).slice(0,m).map(r=>({...r,answers:r.answers.slice(0,h)})),f={qContainer:n,aContainer:t,explContainer:o,nextBtn:l,finalContainer:s,progBar:e},c={currIdx:0,score:0,userAnswers:[]};l.addEventListener("click",v),q(d,c,f,w);function w(r,a,y){r===0&&c.score++,c.userAnswers.push(r);const b=t.getElementsByTagName("button");for(let p=0;p<b.length;p++)b[p].classList.remove("nuclen-quiz-possible-answer"),p===y?b[p].classList.add("nuclen-quiz-answer-correct","nuclen-quiz-pulse"):p===a?b[p].classList.add("nuclen-quiz-answer-wrong"):b[p].classList.add("nuclen-quiz-answer-not-selected"),b[p].disabled=!0;o.innerHTML=`<p>${g(d[c.currIdx].explanation)}</p>`,o.classList.remove("nuclen-quiz-hidden"),l.classList.remove("nuclen-quiz-hidden"),typeof gtag=="function"&&(c.currIdx===0&&gtag("event","nuclen_quiz_start"),gtag("event","nuclen_quiz_answer"))}function v(){if(c.currIdx++,c.currIdx<d.length)return q(d,c,f,w),i.scrollIntoView();const r=()=>O(f,u,d,c,()=>q(d,c,f,w));if(u.enabled&&u.position==="before_results")return M(f,u,r);r()}}window.nuclearEngagementInitQuiz=Q;
