window.NuclenLazyLoadComponent=function(i,n=null){const e=document.getElementById(i);if(!e)return;const t=new IntersectionObserver(r=>{r.forEach(a=>{a.isIntersecting&&(n&&typeof window[n]=="function"&&window[n](),t.disconnect())})},{rootMargin:"0px 0px -200px 0px",threshold:.1});t.observe(e)};function k(i,n){const e=document.querySelector(i);if(!e)return;new IntersectionObserver((r,a)=>{r.forEach(o=>{o.isIntersecting&&o.intersectionRatio===1&&(typeof gtag=="function"&&gtag("event",n),a.unobserve(o.target))})},{root:null,rootMargin:"0px",threshold:1}).observe(e)}const T=new MutationObserver((i,n)=>{const e=document.getElementById("nuclen-quiz-container"),t=document.getElementById("nuclen-summary-container");e&&t&&(k("#nuclen-summary-container","nuclen_summary_view"),k("#nuclen-quiz-container","nuclen_quiz_view"),n.disconnect())});T.observe(document.body,{childList:!0,subtree:!0});window.NuclenLazyLoadComponent("nuclen-quiz-container","nuclearEngagementInitQuiz");function C(...i){console.warn(...i)}function E(...i){console.error(...i)}function M(i){const n=[...i];for(let e=n.length-1;e>0;e--){const t=Math.floor(Math.random()*(e+1));[n[e],n[t]]=[n[t],n[e]]}return n}const N=i=>/.+@.+\..+/.test(i),b=i=>i.replace(/[&<>"']/g,n=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[n]||n),$=async(i,n,e,t)=>{if(!(!t.ajaxUrl||!t.ajaxNonce))try{const r=await fetch(t.ajaxUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({action:"nuclen_save_optin",nonce:t.ajaxNonce,name:i,email:n,url:e})});r.ok||E("[NE] Local opt-in failed",r.status)}catch(r){E("[NE] Local opt-in network error",r)}},B=async(i,n,e)=>{if(e.webhook)try{const t=await fetch(e.webhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:i,email:n})});if(!t.ok)throw E("[NE] Webhook responded with",t.status),new Error(String(t.status))}catch(t){throw E("[NE] Webhook request error",t),t}},O=i=>`
  <div id="nuclen-optin-container" class="nuclen-optin-with-results">
    <p class="nuclen-fg"><strong>${i.promptText}</strong></p>
    <label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
    <input  type="text"  id="nuclen-optin-name">
    <label for="nuclen-optin-email" class="nuclen-fg">Email</label>
    <input  type="email" id="nuclen-optin-email" required>
    <button type="button" id="nuclen-optin-submit">${i.submitLabel}</button>
  </div>`;function S(i,n,e,t){var r,a;i.innerHTML=`
    <div id="nuclen-optin-container">
      <p class="nuclen-fg"><strong>${n.promptText}</strong></p>
      <label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
      <input  type="text"  id="nuclen-optin-name">
      <label for="nuclen-optin-email" class="nuclen-fg">Email *</label>
      <input  type="email" id="nuclen-optin-email" required>
      <div class="nuclen-optin-btn-row">
        <button type="button" id="nuclen-optin-submit">${n.submitLabel}</button>
      </div>
      ${n.mandatory?"":'<div class="nuclen-optin-skip"><a href="#" id="nuclen-optin-skip">Skip &amp; view results</a></div>'}
    </div>`,(r=document.getElementById("nuclen-optin-submit"))==null||r.addEventListener("click",async()=>{const o=document.getElementById("nuclen-optin-name").value.trim(),f=document.getElementById("nuclen-optin-email").value.trim();if(!N(f))return alert("Please enter a valid email");await $(o,f,window.location.href,n);try{await B(o,f,n),e()}catch{alert("Network error – please try again later.")}}),(a=document.getElementById("nuclen-optin-skip"))==null||a.addEventListener("click",o=>{o.preventDefault(),t()})}function H(i){var n;(n=document.getElementById("nuclen-optin-submit"))==null||n.addEventListener("click",async()=>{const e=document.getElementById("nuclen-optin-name").value.trim(),t=document.getElementById("nuclen-optin-email").value.trim();if(!N(t))return alert("Please enter a valid email");await $(e,t,window.location.href,i);try{await B(e,t,i)}catch{alert("Unable to submit. Please try later.")}})}function Q(i,n,e){const{qContainer:t,aContainer:r,explContainer:a,nextBtn:o,finalContainer:f}=i;t.innerHTML="",r.innerHTML="",a.innerHTML="",o.classList.add("nuclen-quiz-hidden"),S(f,n,e,e)}function A(i,n,e,t,r){const{qContainer:a,aContainer:o,explContainer:f,nextBtn:L,finalContainer:p,progBar:h}=i;a.innerHTML="",o.innerHTML="",f.innerHTML="",L.classList.add("nuclen-quiz-hidden"),p.classList.remove("nuclen-quiz-hidden");let u="";n.enabled&&n.position==="with_results"&&(u+=O(n)),u+=`
    <div id="nuclen-quiz-results-title" class="nuclen-fg">${NuclenStrings.your_score}</div>
    <div id="nuclen-quiz-results-score" class="nuclen-fg" aria-live="polite" aria-atomic="true">
      ${t.score} / ${e.length}
    </div>`;const c=t.score===e.length?NuclenStrings.perfect:t.score>e.length/2?NuclenStrings.well_done:NuclenStrings.retake_prompt;u+=`<div id="nuclen-quiz-score-comment" aria-live="polite">${c}</div>`,u+='<div id="nuclen-quiz-result-tabs-container">',e.forEach((v,g)=>{u+=`
      <button class="nuclen-quiz-result-tab"
              onclick="nuclearEngagementShowQuizQuestionDetails(${g})">${g+1}</button>`}),u+='</div><div id="nuclen-quiz-result-details-container" class="nuclen-fg dashboard-box"></div>',NuclenCustomQuizHtmlAfter!=null&&NuclenCustomQuizHtmlAfter.trim()&&(u+=`
      <div id="nuclen-quiz-end-message" class="nuclen-fg">
        ${NuclenCustomQuizHtmlAfter}
      </div>`),u+=`
    <button id="nuclen-quiz-retake-button"
            onclick="nuclearEngagementRetakeQuiz()">${NuclenStrings.retake_test}</button>`,p.innerHTML=u,p.setAttribute("aria-live","polite"),n.enabled&&n.position==="with_results"&&H(n),window.nuclearEngagementShowQuizQuestionDetails=v=>{var y;const g=e[v],q=t.userAnswers[v];document.getElementById("nuclen-quiz-result-details-container").innerHTML=`
      <p class="nuclen-quiz-detail-question">${b(g.question)}</p>
      <p class="nuclen-quiz-detail-correct"><strong>${NuclenStrings.correct}</strong> ${b(g.answers[0])}</p>
      ${q===0?`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${b(g.answers[0])} <span class="nuclen-quiz-checkmark">✔️</span></p>`:`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${b(g.answers[q]??"[No data]")}</p>`}
      <p class="nuclen-quiz-detail-explanation">${b(g.explanation)}</p>`,Array.from(document.getElementsByClassName("nuclen-quiz-result-tab")).forEach(l=>l.classList.remove("nuclen-quiz-result-active-tab")),(y=document.getElementsByClassName("nuclen-quiz-result-tab")[v])==null||y.classList.add("nuclen-quiz-result-active-tab")},window.nuclearEngagementShowQuizQuestionDetails(0),window.nuclearEngagementRetakeQuiz=()=>{t.currIdx=0,t.score=0,t.userAnswers.length=0,p.innerHTML="",p.classList.add("nuclen-quiz-hidden"),h.style.width=`${1/e.length*100}%`,r()},typeof gtag=="function"&&gtag("event","nuclen_quiz_end")}function j(){const i=document.getElementById("nuclen-quiz-container"),n=document.getElementById("nuclen-quiz-question-container"),e=document.getElementById("nuclen-quiz-answers-container"),t=document.getElementById("nuclen-quiz-progress-bar"),r=document.getElementById("nuclen-quiz-final-result-container"),a=document.getElementById("nuclen-quiz-next-button"),o=document.getElementById("nuclen-quiz-explanation-container");if(!i||!n||!e||!t||!r||!a||!o){C("[NE] Quiz markup missing — init aborted.");return}const f=(NuclenSettings==null?void 0:NuclenSettings.questions_per_quiz)??10,L=(NuclenSettings==null?void 0:NuclenSettings.answers_per_question)??4,p={position:NuclenOptinPosition??"with_results",mandatory:!!NuclenOptinMandatory,promptText:NuclenOptinPromptText,submitLabel:NuclenOptinButtonText,enabled:!!window.NuclenOptinEnabled,webhook:window.NuclenOptinWebhook,ajaxUrl:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.url)??"",ajaxNonce:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.nonce)??""},h=postQuizData.filter(l=>{var z;return l.question.trim()&&((z=l.answers[0])==null?void 0:z.trim())}).slice(0,f).map(l=>({...l,answers:l.answers.slice(0,L)})),u={qContainer:n,aContainer:e,explContainer:o,nextBtn:a,finalContainer:r,progBar:t},c={currIdx:0,score:0,userAnswers:[]};a.addEventListener("click",y),v();function v(){const l=h[c.currIdx];n.innerHTML=`
        <div id="nuclen-quiz-question-number" aria-live="polite" aria-atomic="true">
          ${c.currIdx+1}/${h.length}
        </div>
        <div class="nuclen-quiz-title" role="heading" aria-level="2">${b(l.question)}</div>`;const z=M(l.answers.map((s,m)=>({ans:s,idx:m})).filter(s=>s.ans.trim()));e.innerHTML=z.map((s,m)=>`
            <button
              class="nuclen-quiz-answer-button nuclen-quiz-possible-answer"
              data-orig-idx="${s.idx}"
              tabindex="0"
              aria-label="Answer ${m+1}: ${b(s.ans)}"
            >${b(s.ans)}</button>`).join("");const x=z.findIndex(s=>s.idx===0);o.innerHTML="",o.classList.add("nuclen-quiz-hidden"),a.classList.add("nuclen-quiz-hidden"),g();const w=s=>{const m=parseInt(s.getAttribute("data-orig-idx")||"0",10);q(m,z.findIndex(_=>_.idx===m),x),e.removeEventListener("click",d),e.removeEventListener("keydown",I)},d=s=>{const m=s.target;m.matches("button.nuclen-quiz-answer-button")&&w(m)},I=s=>{const m=s.target;m.matches("button.nuclen-quiz-answer-button")&&(s.key==="Enter"||s.key===" ")&&(s.preventDefault(),w(m))};e.addEventListener("click",d),e.addEventListener("keydown",I)}function g(){t.style.width=`${(c.currIdx+1)/h.length*100}%`}function q(l,z,x){l===0&&c.score++,c.userAnswers.push(l);const w=e.getElementsByTagName("button");for(let d=0;d<w.length;d++)w[d].classList.remove("nuclen-quiz-possible-answer"),d===x?w[d].classList.add("nuclen-quiz-answer-correct","nuclen-quiz-pulse"):d===z?w[d].classList.add("nuclen-quiz-answer-wrong"):w[d].classList.add("nuclen-quiz-answer-not-selected"),w[d].disabled=!0;o.innerHTML=`<p>${b(h[c.currIdx].explanation)}</p>`,o.classList.remove("nuclen-quiz-hidden"),a.classList.remove("nuclen-quiz-hidden"),typeof gtag=="function"&&(c.currIdx===0&&gtag("event","nuclen_quiz_start"),gtag("event","nuclen_quiz_answer"))}function y(){if(c.currIdx++,c.currIdx<h.length)return v(),i.scrollIntoView();const l=()=>A(u,p,h,c,v);if(p.enabled&&p.position==="before_results")return Q(u,p,l);l()}}window.nuclearEngagementInitQuiz=j;
