import{e as z}from"../../logger-DwRZMuf8.js";window.NuclenLazyLoadComponent=function(i,n=null){const t=document.getElementById(i);if(!t)return;const e=new IntersectionObserver(o=>{o.forEach(s=>{if(s.isIntersecting){const a=window;n&&typeof a[n]=="function"&&a[n](),e.disconnect()}})},{rootMargin:"0px 0px -200px 0px",threshold:.1});e.observe(t)};function E(i,n){const t=document.querySelector(i);if(!t)return;new IntersectionObserver((o,s)=>{o.forEach(a=>{a.isIntersecting&&a.intersectionRatio===1&&(typeof gtag=="function"&&gtag("event",n),s.unobserve(a.target))})},{root:null,rootMargin:"0px",threshold:1}).observe(t)}const k=new MutationObserver((i,n)=>{const t=document.getElementById("nuclen-quiz-container"),e=document.getElementById("nuclen-summary-container");t&&e&&(E("#nuclen-summary-container","nuclen_summary_view"),E("#nuclen-quiz-container","nuclen_quiz_view"),n.disconnect())});k.observe(document.body,{childList:!0,subtree:!0});window.NuclenLazyLoadComponent("nuclen-quiz-container","nuclearEngagementInitQuiz");function N(i){const n=[...i];for(let t=n.length-1;t>0;t--){const e=Math.floor(Math.random()*(t+1));[n[t],n[e]]=[n[e],n[t]]}return n}const L=i=>/.+@.+\..+/.test(i),g=i=>i.replace(/[&<>"']/g,n=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[n]||n),x=async(i,n,t,e)=>{if(!(!e.ajaxUrl||!e.ajaxNonce))try{const o=await fetch(e.ajaxUrl,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({action:"nuclen_save_optin",nonce:e.ajaxNonce,name:i,email:n,url:t})});o.ok||z("[NE] Local opt-in failed",o.status)}catch(o){z("[NE] Local opt-in network error",o)}},I=async(i,n,t)=>{if(t.webhook)try{const e=await fetch(t.webhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:i,email:n})});if(!e.ok)throw z("[NE] Webhook responded with",e.status),new Error(String(e.status))}catch(e){throw z("[NE] Webhook request error",e),e}},B=i=>`
	<div id="nuclen-optin-container" class="nuclen-optin-with-results">
	<p class="nuclen-fg"><strong>${i.promptText}</strong></p>
	<label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
	<input  type="text"  id="nuclen-optin-name">
	<label for="nuclen-optin-email" class="nuclen-fg">Email</label>
	<input  type="email" id="nuclen-optin-email" required>
	<button type="button" id="nuclen-optin-submit">${i.submitLabel}</button>
	</div>`;function $(i,n,t,e){var o,s;i.innerHTML=`
	<div id="nuclen-optin-container">
		<p class="nuclen-fg"><strong>${n.promptText}</strong></p>
		<label for="nuclen-optin-name"  class="nuclen-fg">Name</label>
		<input  type="text"  id="nuclen-optin-name">
		<label for="nuclen-optin-email" class="nuclen-fg">Email *</label>
		<input  type="email" id="nuclen-optin-email" required>
		<div class="nuclen-optin-btn-row">
		<button type="button" id="nuclen-optin-submit">${n.submitLabel}</button>
		</div>
		${n.mandatory?"":'<div class="nuclen-optin-skip"><a href="#" id="nuclen-optin-skip">Skip &amp; view results</a></div>'}
	</div>`,(o=document.getElementById("nuclen-optin-submit"))==null||o.addEventListener("click",async()=>{const a=document.getElementById("nuclen-optin-name").value.trim(),u=document.getElementById("nuclen-optin-email").value.trim();if(!L(u))return alert("Please enter a valid email");await x(a,u,window.location.href,n);try{await I(a,u,n),t()}catch{alert("Network error – please try again later.")}}),(s=document.getElementById("nuclen-optin-skip"))==null||s.addEventListener("click",a=>{a.preventDefault(),e()})}function _(i){var n;(n=document.getElementById("nuclen-optin-submit"))==null||n.addEventListener("click",async()=>{const t=document.getElementById("nuclen-optin-name").value.trim(),e=document.getElementById("nuclen-optin-email").value.trim();if(!L(e))return alert("Please enter a valid email");await x(t,e,window.location.href,i);try{await I(t,e,i)}catch{alert("Unable to submit. Please try later.")}})}function T(i,n,t){var s;let e="";i.enabled&&i.position==="with_results"&&(e+=B(i)),e+=`
<div id="nuclen-quiz-results-title" class="nuclen-fg">${NuclenStrings.your_score}</div>
<div id="nuclen-quiz-results-score" class="nuclen-fg" aria-live="polite" aria-atomic="true">
${t.score} / ${n.length}
</div>`;const o=t.score===n.length?NuclenStrings.perfect:t.score>n.length/2?NuclenStrings.well_done:NuclenStrings.retake_prompt;return e+=`<div id="nuclen-quiz-score-comment" aria-live="polite">${o}</div>`,e+='<div id="nuclen-quiz-result-tabs-container">',n.forEach((a,u)=>{e+=`
<button class="nuclen-quiz-result-tab" onclick="nuclearEngagementShowQuizQuestionDetails(${u})">${u+1}</button>`}),e+='</div><div id="nuclen-quiz-result-details-container" class="nuclen-fg dashboard-box"></div>',(s=window.NuclenCustomQuizHtmlAfter)!=null&&s.trim()&&(e+=`
<div id="nuclen-quiz-end-message" class="nuclen-fg">
${window.NuclenCustomQuizHtmlAfter}
</div>`),e+=`
<button id="nuclen-quiz-retake-button" onclick="nuclearEngagementRetakeQuiz()">${NuclenStrings.retake_test}</button>`,e}function C(i,n){window.nuclearEngagementShowQuizQuestionDetails=t=>{var s;const e=i[t],o=n.userAnswers[t];document.getElementById("nuclen-quiz-result-details-container").innerHTML=`
<p class="nuclen-quiz-detail-question">${g(e.question)}</p>
<p class="nuclen-quiz-detail-correct"><strong>${NuclenStrings.correct}</strong> ${g(e.answers[0])}</p>
${o===0?`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${g(e.answers[0])} <span class="nuclen-quiz-checkmark">✔️</span></p>`:`<p class="nuclen-quiz-detail-chosen"><strong>${NuclenStrings.your_answer}</strong> ${g(e.answers[o]??"[No data]")}</p>`}
<p class="nuclen-quiz-detail-explanation">${g(e.explanation)}</p>`,Array.from(document.getElementsByClassName("nuclen-quiz-result-tab")).forEach(a=>a.classList.remove("nuclen-quiz-result-active-tab")),(s=document.getElementsByClassName("nuclen-quiz-result-tab")[t])==null||s.classList.add("nuclen-quiz-result-active-tab")},window.nuclearEngagementShowQuizQuestionDetails(0)}function H(i,n,t,e,o){window.nuclearEngagementRetakeQuiz=()=>{i.currIdx=0,i.score=0,i.userAnswers.length=0,n.innerHTML="",n.classList.add("nuclen-quiz-hidden"),t.style.width=`${1/e*100}%`,o()}}function M(i,n,t){const{qContainer:e,aContainer:o,explContainer:s,nextBtn:a,finalContainer:u}=i;e.innerHTML="",o.innerHTML="",s.innerHTML="",a.classList.add("nuclen-quiz-hidden"),$(u,n,t,t)}function O(i,n,t,e,o){const{qContainer:s,aContainer:a,explContainer:u,nextBtn:h,finalContainer:d,progBar:m}=i;s.innerHTML="",a.innerHTML="",u.innerHTML="",h.classList.add("nuclen-quiz-hidden"),d.classList.remove("nuclen-quiz-hidden"),d.innerHTML=T(n,t,e),d.setAttribute("aria-live","polite"),n.enabled&&n.position==="with_results"&&_(n),C(t,e),H(e,d,m,t.length,o),typeof gtag=="function"&&gtag("event","nuclen_quiz_end")}function S(i,n,t){i.style.width=`${(n+1)/t*100}%`}function q(i,n,t,e){const{qContainer:o,aContainer:s,explContainer:a,nextBtn:u,progBar:h}=t,d=i[n.currIdx];o.innerHTML=`
	<div id="nuclen-quiz-question-number" aria-live="polite" aria-atomic="true">
		${n.currIdx+1}/${i.length}
	</div>
	<div class="nuclen-quiz-title" role="heading" aria-level="2">${g(d.question)}</div>`;const m=N(d.answers.map((r,l)=>({ans:r,idx:l})).filter(r=>r.ans.trim()));s.innerHTML=m.map((r,l)=>`
		<button
			class="nuclen-quiz-answer-button nuclen-quiz-possible-answer"
			data-orig-idx="${r.idx}"
			data-testid="quiz-answer"
			tabindex="0"
			aria-label="Answer ${l+1}: ${g(r.ans)}"
		>${g(r.ans)}</button>`).join("");const w=m.findIndex(r=>r.idx===0);a.innerHTML="",a.classList.add("nuclen-quiz-hidden"),u.classList.add("nuclen-quiz-hidden"),S(h,n.currIdx,i.length);const c=r=>{const l=parseInt(r.getAttribute("data-orig-idx")||"0",10);e(l,m.findIndex(y=>y.idx===l),w),s.removeEventListener("click",f),s.removeEventListener("keydown",v)},f=r=>{const l=r.target;l.matches("button.nuclen-quiz-answer-button")&&c(l)},v=r=>{const l=r.target;l.matches("button.nuclen-quiz-answer-button")&&(r.key==="Enter"||r.key===" ")&&(r.preventDefault(),c(l))};s.addEventListener("click",f),s.addEventListener("keydown",v)}function Q(){const i=document.getElementById("nuclen-quiz-container"),n=document.getElementById("nuclen-quiz-question-container"),t=document.getElementById("nuclen-quiz-answers-container"),e=document.getElementById("nuclen-quiz-progress-bar"),o=document.getElementById("nuclen-quiz-final-result-container"),s=document.getElementById("nuclen-quiz-next-button"),a=document.getElementById("nuclen-quiz-explanation-container");if(!i||!n||!t||!e||!o||!s||!a)return;const u=(NuclenSettings==null?void 0:NuclenSettings.questions_per_quiz)??10,h=(NuclenSettings==null?void 0:NuclenSettings.answers_per_question)??4,d={position:window.NuclenOptinPosition??"with_results",mandatory:!!window.NuclenOptinMandatory,promptText:window.NuclenOptinPromptText??"",submitLabel:window.NuclenOptinButtonText??"",enabled:!!window.NuclenOptinEnabled,webhook:window.NuclenOptinWebhook??"",ajaxUrl:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.url)??"",ajaxNonce:(NuclenOptinAjax==null?void 0:NuclenOptinAjax.nonce)??""};if(typeof postQuizData>"u"||!Array.isArray(postQuizData))return;const m=postQuizData.filter(r=>{var l;return r.question.trim()&&((l=r.answers[0])==null?void 0:l.trim())}).slice(0,u).map(r=>({...r,answers:r.answers.slice(0,h)})),w={qContainer:n,aContainer:t,explContainer:a,nextBtn:s,finalContainer:o,progBar:e},c={currIdx:0,score:0,userAnswers:[]};s.addEventListener("click",v),q(m,c,w,f);function f(r,l,y){r===0&&c.score++,c.userAnswers.push(r);const b=t.getElementsByTagName("button");for(let p=0;p<b.length;p++)b[p].classList.remove("nuclen-quiz-possible-answer"),p===y?b[p].classList.add("nuclen-quiz-answer-correct","nuclen-quiz-pulse"):p===l?b[p].classList.add("nuclen-quiz-answer-wrong"):b[p].classList.add("nuclen-quiz-answer-not-selected"),b[p].disabled=!0;a.innerHTML=`<p>${g(m[c.currIdx].explanation)}</p>`,a.classList.remove("nuclen-quiz-hidden"),s.classList.remove("nuclen-quiz-hidden"),typeof gtag=="function"&&(c.currIdx===0&&gtag("event","nuclen_quiz_start"),gtag("event","nuclen_quiz_answer"))}function v(){if(c.currIdx++,c.currIdx<m.length)return q(m,c,w,f),i.scrollIntoView();const r=()=>O(w,d,m,c,()=>q(m,c,w,f));if(d.enabled&&d.position==="before_results")return M(w,d,r);r()}}window.nuclearEngagementInitQuiz=Q;
//# sourceMappingURL=nuclen-front.js.map
