name: Frontend Quality Assurance

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-tests:
    name: Node.js ${{ matrix.node }} - Frontend Tests
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node: ['18', '20', '22']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript type checking
        run: npm run type-check

      - name: Run Vitest unit tests
        run: npm test -- --coverage

      - name: Build production assets
        run: npm run build

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: frontend-tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Setup WordPress test environment
        run: |
          docker-compose -f docker-compose.debug.yml up -d
          sleep 30

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: Run accessibility tests
        run: npm run test:accessibility

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30